version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=780155373008.dkr.ecr.us-east-1.amazonaws.com/flamingo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t flamingo .
      - docker tag flamingo:latest 780155373008.dkr.ecr.us-east-1.amazonaws.com/flamingo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 780155373008.dkr.ecr.us-east-1.amazonaws.com/flamingo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"flamingo","imageUri":"%s"}]' 780155373008.dkr.ecr.us-east-1.amazonaws.com/flamingo:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json